### ISSUE TITLE
Cannot plot flat fields as arrows

### ISSUE THREAD

**Issue by jzwar** [tataratat/gustaf#120]
There seems to be an issue with arrow plots in gustaf

Version:
`splinepy` : 0.0.19
`gustaf` : 0.0.9

# Showcase
This works fine:
```python
import gustaf as gus
import numpy as np
a = gus.Bezier(
    degrees=[1,1,1],
    control_points=gus.spline.splinepy.utils.data.cartesian_product(
        [np.array([0,1]) for _ in range(3)]
    )
)
a.show()
aa = a.copy()
a.spline_data["field"] = aa
a.show_options["arrow_data"] = "field"
a.show() # works just fine
```
Error occurs when setting one dimension to zero
```python
aa.cps[:,1] = 0
a.show() # ERROR
```

Error text:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/gustaf/spline/base.py", line 214, in show
    return show(self, **kwargs)
  File "<path>/gustaf/spline/base.py", line 79, in show
    things_to_show = visualize.make_showable(spline)
  File "<path>/gustaf/spline/visualize.py", line 92, in make_showable
    return eval(f"_{spline.show_options._backend}_showable(spline)")
  File "<string>", line 1, in <module>
  File "<path>/gustaf/spline/visualize.py", line 211, in _vedo_showable
    sampled_spline.vertex_data[
  File "<path>/gustaf/helpers/data.py", line 504, in __setitem__
    self._validate_len(value, raise_=True)
  File "<path>/gustaf/helpers/data.py", line 462, in _validate_len
    raise ValueError(
ValueError: Expected (58808) length data, Given (len(value))
```

**Comment by j042** [comment]
> There seems to be an issue with arrow plots in gustaf
> 
> Version: `splinepy` : 0.0.19 `gustaf` : 0.0.9
> 
> # Showcase
> This works fine:
> 
> ```python
> import gustaf as gus
> import numpy as np
> a = gus.Bezier(
>     degrees=[1,1],
>     control_points=gus.spline.splinepy.utils.data.cartesian_product(
>         [np.array([0,1]) for _ in range(3)]
>     )
> )
> a.show()
> aa = a.copy()
> a.spline_data["field"] = aa
> a.show_options["arrow_data"] = aa
I guess you meant
`a.show_options["arrow_data"] = "field"`.

I tried this example with freshly pip-installed gustaf and splinepy, but couldn't reproduced the error
<img width="393" alt="Screenshot 2023-04-26 at 22 32 00" src="https://user-images.githubusercontent.com/47114801/234695476-6721513c-5a3a-4665-8090-047710247375.png">

**Comment by jzwar** [comment]
Sorry there was a typo in the script... I updated it. Still produces the error

**Comment by jzwar** [comment]
It seems it only happens in 3D

**Comment by jzwar** [comment]
@j042 any ideas?

**Comment by j042** [comment]
yes
