### ISSUE TITLE
Some slots are not instantiated or not accessible with out previous function call

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/gustaf#24]
For example in the Edges class the slot attribute `outlines` is only available after calling the function `get_outlines()`. If this attribute is not supposed to be called directly, "hide" it by making it private `_outlines` or create a getter function to make sure it gets correctly updated.

I have just encountered this in this specific case, but after looking briefly at the code this issue is also present in other cases.

**Comment by j042** [comment]
That is desired behavior for now. I've tried to clarify the intention  [here](https://github.com/tataratat/gustaf/pull/20#issuecomment-1210286364). It is mainly to support in-place changes, while providing option to get saved values. That will be probably replaced by some sort of "latest-saved-value-retriever" helper class and possibly get rid of "get_" part of the functions.
