### ISSUE TITLE
tH-1: Splinepy not installed; better notification

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/gustaf#29]
Currently if `splinepy` is not installed, the spline "module" will be initialized with "cannot initialize spline modules".

This can lead to very confusing errors. The easiest way to fix this is not to load BSpline in the root __init__ file. This option is not wanted due to this limiting the possibility of directly accessing the Spline component from the root namespace. 

Another option is to create a python class which throws an error if any attribute is called from this class. This class can then overwrite the modules that should be loaded in the root namespace but can not.

**Comment by j042** [comment]
#33
