### ISSUE TITLE
Mesh creation routines

### ISSUE THREAD

**Issue by CodeFloh** [tataratat/gustaf#41]
There are 2D and 3D creation routines in my groups branch. Notably:

- `quad_block_mesh`
- `tri_block_mesh`
- `hexa_block_mesh`
- `tet_block_mesh`

The simplex creation routines rely on `simplexify` and `extrude_to_tet` routines.

All the code related to groups is at the end of the routines and could easily be removed (including relevant function parameters).

See:

- https://github.com/CodeFloh/gustaf/blob/ft-vertex-and-face-groups/gustaf/create/faces.py
- https://github.com/CodeFloh/gustaf/blob/ft-vertex-and-face-groups/gustaf/create/volumes.py

**Comment by clemens-fricke** [comment]
quad_block and hexa_block are implemented with #58, I am not sure if @deltaLuki used or knew about this implimentation.

**Comment by LinusKnecht** [comment]
I will start working on ```simplexify``` and ```extrude_to_tet```. Is the implementation in 

- ```simplexify()``` --> ```nutils.create.faces.py``` 
- ```extrude_to_tet()``` --> ```nutils.create.volumes.py``` 

correct?
