### ISSUE TITLE
Providing geometric primitives as splines

### ISSUE THREAD

**Issue by Roxana-P** [tataratat/gustaf#46]
Fast prototyping involves the creation of new geometries. While the ad-hoc construction of splines is counterintuitive for most users, many geometries can be created by merging and modifying a set of geometric primitives. Thus, the provision of basis spline shapes facilitates the use of gustaf. 
I propose the implementation of these primitives in `gustaf/spline.create.py`: 
- Circle
- Disk
- Rectangle
- Box
- Cone
- Pyramid
- Torus
- Sphere
Each geometry is created by a function with the same name. It returns a geometry represented by the simplest spline type, the lowest degree and least number of elements - still capable of representing the geometry. 
If needed, a user can use existing functions to convert the spline type, elevate the degree or insert knots.

**Comment by clemens-fricke** [comment]
Merged well done!
Are there residuals that are not implemented or can this be closed?
