### ISSUE TITLE
ft - gustaf simple meshio IO - can be copied from gustav

### ISSUE THREAD

**Issue by deltaLuki** [tataratat/gustaf#64]

**Comment by deltaLuki** [comment]
Where can I find the meshio in gustav? @j042

**Comment by j042** [comment]
nowhere. you can add a module and use [ModuleImportRaiser](https://github.com/tataratat/gustaf/blob/638e1b6d50a56b442fe66ce9f294d77f47a08180/gustaf/helpers/raise_if.py#L41) in case it is not available in system

**Comment by clemens-fricke** [comment]
#67 So there was something in `gustav` in the load.py file. I just adapted it.
