### ISSUE TITLE
(Re)Adding Free Form Deformation 

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/gustaf#8]
The functionality of computing a Free Form Deformation directly inside `gustaf` should be added. The functionality was already present in the `gustav` package and now needs to be re-added. 

The original free form deformation code is available internally in the TU Wien `gustav` repository and is available to adapt to the new architecture. 

FFD
------

Free Form Deformation is the application of spline onto a mesh. This deforms the mesh in correspondence to the deformation defined by the spline. This gives, for example, an efficient method of deforming a computational mesh during shape optimization applications.

**Comment by weihnachten033** [comment]
#15 
Implements this. 
Missing parts:

- partial FFD
- plotting

**Comment by clemens-fricke** [comment]
Pull Request accepted. Close issue!

Partial FFD needs to be implemented separately.
